"""add_era_upload_updated_at

Revision ID: 58cdb2b0a0e6
Revises: c2a13d045adb
Create Date: 2026-01-21 22:41:19.748348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58cdb2b0a0e6'
down_revision: Union[str, Sequence[str], None] = 'c2a13d045adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('era_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('era_uploads', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
