"""Add interactions relationships and custom attributes

Revision ID: 6a5bf5e8fc0a
Revises: 6fc4b9f624b1
Create Date: 2026-01-21 20:23:50.263471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5bf5e8fc0a'
down_revision: Union[str, Sequence[str], None] = '6fc4b9f624b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('remote_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_id'), ['id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_member_id', sa.Integer(), nullable=True),
    sa.Column('to_member_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['to_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_id'), ['id'], unique=False)

    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.alter_column('verification_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'browser'"))
        batch_op.drop_column('details')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_attributes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('custom_attributes')

    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.TEXT(), nullable=True))
        batch_op.alter_column('verification_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'browser'"))

    op.create_table('era_uploads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('record_count', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'complete'"), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('era_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_era_uploads_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_uploads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_uploads_filename'), ['filename'], unique=False)

    op.create_table('era_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('upload_id', sa.INTEGER(), nullable=True),
    sa.Column('enrolment_state', sa.VARCHAR(length=1), nullable=True),
    sa.Column('transaction_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('federal_direct_indicator', sa.VARCHAR(length=1), nullable=True),
    sa.Column('title', sa.VARCHAR(length=10), nullable=True),
    sa.Column('given_names', sa.VARCHAR(length=25), nullable=True),
    sa.Column('surname', sa.VARCHAR(length=25), nullable=True),
    sa.Column('surname_normalized', sa.VARCHAR(length=25), nullable=True),
    sa.Column('given_names_normalized', sa.VARCHAR(length=25), nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(length=10), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=1), nullable=True),
    sa.Column('habitation_name', sa.VARCHAR(length=25), nullable=True),
    sa.Column('flat_number', sa.VARCHAR(length=6), nullable=True),
    sa.Column('street_number', sa.VARCHAR(length=6), nullable=True),
    sa.Column('street_name', sa.VARCHAR(length=25), nullable=True),
    sa.Column('street_type', sa.VARCHAR(length=7), nullable=True),
    sa.Column('locality_name', sa.VARCHAR(length=25), nullable=True),
    sa.Column('post_code', sa.VARCHAR(length=4), nullable=True),
    sa.Column('state', sa.VARCHAR(length=3), nullable=True),
    sa.Column('full_address', sa.VARCHAR(length=108), nullable=True),
    sa.Column('enrolled_address_dpid', sa.VARCHAR(length=8), nullable=True),
    sa.Column('walk_number', sa.VARCHAR(length=5), nullable=True),
    sa.Column('enrolled_date', sa.VARCHAR(length=10), nullable=True),
    sa.Column('eligibility_flag', sa.VARCHAR(length=1), nullable=True),
    sa.Column('gpv_indicator', sa.VARCHAR(length=1), nullable=True),
    sa.Column('new_enrolment_flag', sa.VARCHAR(length=1), nullable=True),
    sa.Column('postal_address', sa.VARCHAR(length=57), nullable=True),
    sa.Column('postal_address_dpid', sa.VARCHAR(length=8), nullable=True),
    sa.Column('federal_division', sa.VARCHAR(length=25), nullable=True),
    sa.Column('federal_division_pre_redistribution', sa.VARCHAR(length=25), nullable=True),
    sa.Column('state_district', sa.VARCHAR(length=25), nullable=True),
    sa.Column('state_district_pre_redistribution', sa.VARCHAR(length=25), nullable=True),
    sa.Column('local_government_area', sa.VARCHAR(length=25), nullable=True),
    sa.Column('lga_pre_redistribution', sa.VARCHAR(length=25), nullable=True),
    sa.Column('sa1', sa.VARCHAR(length=7), nullable=True),
    sa.Column('mailing_name', sa.VARCHAR(length=62), nullable=True),
    sa.Column('mailing_address_line1', sa.VARCHAR(length=40), nullable=True),
    sa.Column('mailing_address_line2', sa.VARCHAR(length=40), nullable=True),
    sa.Column('mailing_address_line3', sa.VARCHAR(length=40), nullable=True),
    sa.Column('mailing_address_line4', sa.VARCHAR(length=40), nullable=True),
    sa.Column('prev_enrolment_state', sa.VARCHAR(length=1), nullable=True),
    sa.Column('prev_transaction_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('dual_enrolment_state', sa.VARCHAR(length=1), nullable=True),
    sa.Column('dual_transaction_number', sa.VARCHAR(length=8), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['era_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('era_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_era_records_transaction_number'), ['transaction_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_records_surname_normalized'), ['surname_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_records_surname'), ['surname'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_records_street_name'), ['street_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_records_state_district'), ['state_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_records_post_code'), ['post_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_records_locality_name'), ['locality_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_records_given_names_normalized'), ['given_names_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_records_federal_division'), ['federal_division'], unique=False)
        batch_op.create_index(batch_op.f('idx_era_unique_person'), ['surname_normalized', 'given_names_normalized', 'full_address'], unique=1)
        batch_op.create_index(batch_op.f('idx_era_surname_locality'), ['surname_normalized', 'locality_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_era_postcode_surname'), ['post_code', 'surname_normalized'], unique=False)
        batch_op.create_index(batch_op.f('idx_era_federal_division'), ['federal_division', 'surname_normalized'], unique=False)

    op.create_table('era_matches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=True),
    sa.Column('era_record_id', sa.INTEGER(), nullable=True),
    sa.Column('overall_score', sa.INTEGER(), nullable=True),
    sa.Column('name_score', sa.INTEGER(), nullable=True),
    sa.Column('address_score', sa.INTEGER(), nullable=True),
    sa.Column('is_verified', sa.INTEGER(), nullable=True),
    sa.Column('matched_at', sa.DATETIME(), nullable=True),
    sa.Column('verified_by', sa.INTEGER(), nullable=True),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('federal_division', sa.VARCHAR(length=25), nullable=True),
    sa.Column('state_district', sa.VARCHAR(length=25), nullable=True),
    sa.Column('local_government_area', sa.VARCHAR(length=25), nullable=True),
    sa.ForeignKeyConstraint(['era_record_id'], ['era_records.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('era_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_era_matches_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_matches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_era_matches_era_record_id'), ['era_record_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_era_match_member'), ['member_id', 'overall_score'], unique=False)

    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_id'))

    op.drop_table('relationships')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_id'))

    op.drop_table('interactions')
    # ### end Alembic commands ###
