"""Add details to CheckResult

Revision ID: 6fc4b9f624b1
Revises: 9fe865df3df3
Create Date: 2025-11-27 13:10:58.803397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc4b9f624b1'
down_revision: Union[str, Sequence[str], None] = '9fe865df3df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
