"""Update schema

Revision ID: f540f9f96199
Revises: 33a98ea80f78
Create Date: 2025-11-25 22:54:09.699608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f540f9f96199'
down_revision: Union[str, Sequence[str], None] = '33a98ea80f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('members', sa.Column('party_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('members') as batch_op:
        batch_op.create_foreign_key('fk_members_party_id_parties', 'parties', ['party_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'party_id')
    # ### end Alembic commands ###
